<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of Bible booknames codes including
these four compulsory fields:
    An English book name (as a comment only)
    A three character reference code (upper case, no spaces, begins with a letter)
        This reference code should reflect book contents (not book names) and is used to link to other tables.
        These reference codes are guaranteed to be stable after V1.00
            i.e., they will not change or be reused for different books.
    A reference number (1..255 for processing only - not necessarily consecutive or sequential)
        Reference numbers are guaranteed to be stable after V1.00
            i.e., they will not change or be reused for different books.
        Can be used as a unique ID instead of the reference code if you prefer an integer.
        1..66 are guaranteed to match the common Protestant Bible book orders.
        245..255 are reserved for user defined books and are not defined here.
    A sequence number or typical book order number (1..999 for comparing the order only - not necessarily consecutive)
        Only to be used if there is no better information about which order that books are intended to be published in.
        Only the relative values of this field is important (smaller or bigger) - the actual values are meaningless.
and then these optional fields (optional because not all systems handle the less common or more disputed books)
    The number of expected chapters in this book (alternatives are separated by commas).
        This is not authorative, but can assist in identifying books where the encoding is otherwise ambiguous.
    The SBL abbreviation (can include spaces)
    The OSIS abbrevation (no spaces but may begin with a digit)
    The Sword abbreviation
    The 1-2 digit CCEL id number
    The three-character USFM abbreviation (no spaces but may begin with a digit)
    The two-digit USFM id number
        UBS Paratext uses both the number and the abbreviation above (and USFM format)
    The three-digit USX id number
        UBS Paratext can export to USX files
    The 1-2 digit Bibledit id number
    The three-character NET Bible abbreviation
    The 2-4 character Bible abbreviation used for the Robinson-Pierpont Byzantine Greek text
    Alternative book codes (separated by commas)
        This is not precise but roughly shows which book this book might be confused with.
        It is used for automatic mapping of book codes (also using the expected number of chapters)
Most of the above fields should individually be unique, but there are some many-to-one mappings.
    e.g., Paratext uses the same code for Ezra as for Ezra-Nehemiah. (We make available separate codes.)

The information in this table should be language agnostic although English is used as a meta-language.
It should also be independent of any theological judgements but mostly based on historical publications.
The main aim is to supply an inventory of book codes which are recognised by the BibleOrgSsy Bible Organisational System.

Deutero-canonical/Apocryphal and less common books are included, even pseudegrapha.
"Combined" books are included.
This table does not infer any information about the quality or theological usefulness of any particular book.
This table does not infer any information about the presence or the order of the books within any particular publication.
This table is not authoritative about the number of chapters (or verses) in any given book in any particular publication.
There should be exactly one entry for each possible Bible book which is printed separately in some publications
    and one entry for each possible combination of those Bible books.
For example:
    If Ezra and Nehemiah are sometimes published as individual books, and sometimes combined, there should be three entries in this database.
    If Hebrew Esther and Greek Esther are sometimes published as individual books, and sometimes combined, there should be 3 entries in this database.
        However, if Greek Esther was never published singly, but only in combination with Hebrew Esther, there would only be 2 entries (Hebrew Esther and Combined Esther).
    This is because mappings between/across Bible books in different publications will be dependent on this file.
        (If it's JUST that chapters and verses are divided up differently WITHIN a book, that's handled elsewhere.)
    If a book is a translation of another book, that is not usually a good enough reason to include multiple entries here
        (unless say, both the original and a translation were published in the same "Bible").

This file can never adequately represent all possible historical Bible books codes (and their mappings),
    especially since it attempts to avoid including historic codes which were not consistent or logical.

The data is preceded by a header of the same format as an OSIS header.

Note that the data is supplied as XML elements (not attributes).

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

Not sure where the SWORD entry belongs:   {"SIRACH (PROLOGUE)", "SirP"},		// Sirach (Prologue)

See the supplied BibleBooksCodes.ReadMe.txt for more details.
-->

<!DOCTYPE BibleBooksCodes [
    <!ELEMENT BibleBooksCodes (header,BibleBookCodes+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier+,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleBookCodes (nameEnglish,referenceAbbreviation,referenceNumber,sequenceNumber,expectedChapters?,SBLAbbreviation?,OSISAbbreviation?,SwordAbbreviation?,
                        CCELNumber?,USFMAbbreviation?,USFMNumber?,USXNumber?,BibleditNumber?,NETBibleAbbreviation?,ByzantineAbbreviation?,possibleAlternativeBooks?)>
            <!ELEMENT nameEnglish (#PCDATA)>
            <!ELEMENT referenceAbbreviation (#PCDATA)>
            <!ELEMENT referenceNumber (#PCDATA)>
            <!ELEMENT sequenceNumber (#PCDATA)>
            <!ELEMENT expectedChapters (#PCDATA)>
            <!ELEMENT SBLAbbreviation (#PCDATA)>
            <!ELEMENT OSISAbbreviation (#PCDATA)>
            <!ELEMENT SwordAbbreviation (#PCDATA)>
            <!ELEMENT CCELNumber (#PCDATA)>
            <!ELEMENT USFMAbbreviation (#PCDATA)>
            <!ELEMENT USFMNumber (#PCDATA)>
            <!ELEMENT USXNumber (#PCDATA)>
            <!ELEMENT BibleditNumber (#PCDATA)>
            <!ELEMENT NETBibleAbbreviation (#PCDATA)>
            <!ELEMENT ByzantineAbbreviation (#PCDATA)>
            <!ELEMENT possibleAlternativeBooks (#PCDATA)>
]>

<BibleBooksCodes>

  <header>
    <work>
      <version>0.64</version>
      <date>2012-07-13</date>
      <title>Bible books codes list</title>
      <contributor role="com">Robert Hunt</contributor>
      <identifier type="URL">http://www.sbl-site.org/publications/publishingwithsbl.aspx</identifier>
      <identifier type="URL">http://www.bibletechnologies.net</identifier>
      <identifier type="URL">http://lc.bfbs.org.uk/news.php?item.9.4</identifier>
      <identifier type="URL">http://lc.bfbs.org.uk/request.php?canonicalissuesinparatext.pdf</identifier>
      <rights>Public Domain</rights>
    </work>
  </header>

<!-- Old Testament -->
  <BibleBookCodes>
    <nameEnglish>Genesis / 1 Moses</nameEnglish>
    <referenceAbbreviation>GEN</referenceAbbreviation>
    <referenceNumber>1</referenceNumber>
    <sequenceNumber>20</sequenceNumber>
    <expectedChapters>50</expectedChapters>
    <SBLAbbreviation>Gen</SBLAbbreviation>
    <OSISAbbreviation>Gen</OSISAbbreviation>
    <SwordAbbreviation>Gen</SwordAbbreviation>
    <CCELNumber>1</CCELNumber>
    <USFMAbbreviation>Gen</USFMAbbreviation>
    <USFMNumber>01</USFMNumber>
    <USXNumber>001</USXNumber>
    <BibleditNumber>1</BibleditNumber>
    <NETBibleAbbreviation>Gen</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Exodus / 2 Moses</nameEnglish>
    <referenceAbbreviation>EXO</referenceAbbreviation>
    <referenceNumber>2</referenceNumber>
    <sequenceNumber>22</sequenceNumber>
    <expectedChapters>40</expectedChapters>
    <SBLAbbreviation>Exod</SBLAbbreviation>
    <OSISAbbreviation>Exod</OSISAbbreviation>
    <SwordAbbreviation>Exod</SwordAbbreviation>
    <CCELNumber>2</CCELNumber>
    <USFMAbbreviation>Exo</USFMAbbreviation>
    <USFMNumber>02</USFMNumber>
    <USXNumber>002</USXNumber>
    <BibleditNumber>2</BibleditNumber>
    <NETBibleAbbreviation>Exo</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Leviticus / 3 Moses</nameEnglish>
    <referenceAbbreviation>LEV</referenceAbbreviation>
    <referenceNumber>3</referenceNumber>
    <sequenceNumber>24</sequenceNumber>
    <expectedChapters>27</expectedChapters>
    <SBLAbbreviation>Lev</SBLAbbreviation>
    <OSISAbbreviation>Lev</OSISAbbreviation>
    <SwordAbbreviation>Lev</SwordAbbreviation>
    <CCELNumber>3</CCELNumber>
    <USFMAbbreviation>Lev</USFMAbbreviation>
    <USFMNumber>03</USFMNumber>
    <USXNumber>003</USXNumber>
    <BibleditNumber>3</BibleditNumber>
    <NETBibleAbbreviation>Lev</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Numbers / 4 Moses</nameEnglish>
    <referenceAbbreviation>NUM</referenceAbbreviation>
    <referenceNumber>4</referenceNumber>
    <sequenceNumber>26</sequenceNumber>
    <expectedChapters>36</expectedChapters>
    <SBLAbbreviation>Num</SBLAbbreviation>
    <OSISAbbreviation>Num</OSISAbbreviation>
    <SwordAbbreviation>Num</SwordAbbreviation>
    <CCELNumber>4</CCELNumber>
    <USFMAbbreviation>Num</USFMAbbreviation>
    <USFMNumber>04</USFMNumber>
    <USXNumber>004</USXNumber>
    <BibleditNumber>4</BibleditNumber>
    <NETBibleAbbreviation>Num</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Deuteronomy / 5 Moses</nameEnglish>
    <referenceAbbreviation>DEU</referenceAbbreviation>
    <referenceNumber>5</referenceNumber>
    <sequenceNumber>28</sequenceNumber>
    <expectedChapters>34</expectedChapters>
    <SBLAbbreviation>Deut</SBLAbbreviation>
    <OSISAbbreviation>Deut</OSISAbbreviation>
    <SwordAbbreviation>Deut</SwordAbbreviation>
    <CCELNumber>5</CCELNumber>
    <USFMAbbreviation>Deu</USFMAbbreviation>
    <USFMNumber>05</USFMNumber>
    <USXNumber>005</USXNumber>
    <BibleditNumber>5</BibleditNumber>
    <NETBibleAbbreviation>Deu</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Joshua / Joshua son of Nun</nameEnglish>
    <referenceAbbreviation>JOS</referenceAbbreviation>
    <referenceNumber>6</referenceNumber>
    <sequenceNumber>30</sequenceNumber>
    <expectedChapters>24</expectedChapters>
    <SBLAbbreviation>Josh</SBLAbbreviation>
    <OSISAbbreviation>Josh</OSISAbbreviation>
    <SwordAbbreviation>Josh</SwordAbbreviation>
    <CCELNumber>6</CCELNumber>
    <USFMAbbreviation>Jos</USFMAbbreviation>
    <USFMNumber>06</USFMNumber>
    <USXNumber>006</USXNumber>
    <BibleditNumber>6</BibleditNumber>
    <NETBibleAbbreviation>Jos</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Judges</nameEnglish>
    <referenceAbbreviation>JDG</referenceAbbreviation>
    <referenceNumber>7</referenceNumber>
    <sequenceNumber>32</sequenceNumber>
    <expectedChapters>21</expectedChapters>
    <SBLAbbreviation>Judg</SBLAbbreviation>
    <OSISAbbreviation>Judg</OSISAbbreviation>
    <SwordAbbreviation>Judg</SwordAbbreviation>
    <CCELNumber>7</CCELNumber>
    <USFMAbbreviation>Jdg</USFMAbbreviation>
    <USFMNumber>07</USFMNumber>
    <USXNumber>007</USXNumber>
    <BibleditNumber>7</BibleditNumber>
    <NETBibleAbbreviation>Jdg</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Ruth</nameEnglish>
    <referenceAbbreviation>RUT</referenceAbbreviation>
    <referenceNumber>8</referenceNumber>
    <sequenceNumber>34</sequenceNumber>
    <expectedChapters>4</expectedChapters>
    <SBLAbbreviation>Ruth</SBLAbbreviation>
    <OSISAbbreviation>Ruth</OSISAbbreviation>
    <SwordAbbreviation>Ruth</SwordAbbreviation>
    <CCELNumber>8</CCELNumber>
    <USFMAbbreviation>Rut</USFMAbbreviation>
    <USFMNumber>08</USFMNumber>
    <USXNumber>008</USXNumber>
    <BibleditNumber>8</BibleditNumber>
    <NETBibleAbbreviation>Rut</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Samuel / 1 Kingdoms / 1 Kings</nameEnglish>
    <referenceAbbreviation>SA1</referenceAbbreviation>
    <referenceNumber>9</referenceNumber>
    <sequenceNumber>38</sequenceNumber>
    <expectedChapters>31</expectedChapters>
    <SBLAbbreviation>1 Sam</SBLAbbreviation>
    <OSISAbbreviation>1Sam</OSISAbbreviation>
    <SwordAbbreviation>1Sam</SwordAbbreviation>
    <CCELNumber>9</CCELNumber>
    <USFMAbbreviation>1Sa</USFMAbbreviation>
    <USFMNumber>09</USFMNumber>
    <USXNumber>009</USXNumber>
    <BibleditNumber>9</BibleditNumber>
    <NETBibleAbbreviation>1Sa</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>2 Samuel / 2 Kingdoms / 2 Kings</nameEnglish>
    <referenceAbbreviation>SA2</referenceAbbreviation>
    <referenceNumber>10</referenceNumber>
    <sequenceNumber>40</sequenceNumber>
    <expectedChapters>24</expectedChapters>
    <SBLAbbreviation>2 Sam</SBLAbbreviation>
    <OSISAbbreviation>2Sam</OSISAbbreviation>
    <SwordAbbreviation>2Sam</SwordAbbreviation>
    <CCELNumber>10</CCELNumber>
    <USFMAbbreviation>2Sa</USFMAbbreviation>
    <USFMNumber>10</USFMNumber>
    <USXNumber>010</USXNumber>
    <BibleditNumber>10</BibleditNumber>
    <NETBibleAbbreviation>2Sa</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Kings / 3 Kingdoms / 3 Kings</nameEnglish>
    <referenceAbbreviation>KI1</referenceAbbreviation>
    <referenceNumber>11</referenceNumber>
    <sequenceNumber>44</sequenceNumber>
    <expectedChapters>22</expectedChapters>
    <SBLAbbreviation>1 Kgs</SBLAbbreviation>
    <OSISAbbreviation>1Kgs</OSISAbbreviation>
    <SwordAbbreviation>1Kgs</SwordAbbreviation>
    <CCELNumber>11</CCELNumber>
    <USFMAbbreviation>1Ki</USFMAbbreviation>
    <USFMNumber>11</USFMNumber>
    <USXNumber>011</USXNumber>
    <BibleditNumber>11</BibleditNumber>
    <NETBibleAbbreviation>1Ki</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>2 Kings / 4 Kingdoms / 4 Kings</nameEnglish>
    <referenceAbbreviation>KI2</referenceAbbreviation>
    <referenceNumber>12</referenceNumber>
    <sequenceNumber>46</sequenceNumber>
    <expectedChapters>25</expectedChapters>
    <SBLAbbreviation>2 Kgs</SBLAbbreviation>
    <OSISAbbreviation>2Kgs</OSISAbbreviation>
    <SwordAbbreviation>2Kgs</SwordAbbreviation>
    <CCELNumber>12</CCELNumber>
    <USFMAbbreviation>2Ki</USFMAbbreviation>
    <USFMNumber>12</USFMNumber>
    <USXNumber>012</USXNumber>
    <BibleditNumber>12</BibleditNumber>
    <NETBibleAbbreviation>2Ki</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Chronicles / 1 Paralipomenon</nameEnglish>
    <referenceAbbreviation>CH1</referenceAbbreviation>
    <referenceNumber>13</referenceNumber>
    <sequenceNumber>50</sequenceNumber>
    <expectedChapters>29</expectedChapters>
    <SBLAbbreviation>1 Chr</SBLAbbreviation>
    <OSISAbbreviation>1Chr</OSISAbbreviation>
    <SwordAbbreviation>1Chr</SwordAbbreviation>
    <CCELNumber>13</CCELNumber>
    <USFMAbbreviation>1Ch</USFMAbbreviation>
    <USFMNumber>13</USFMNumber>
    <USXNumber>013</USXNumber>
    <BibleditNumber>13</BibleditNumber>
    <NETBibleAbbreviation>1Ch</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>2 Chronicles / 2 Paralipomenon</nameEnglish>
    <referenceAbbreviation>CH2</referenceAbbreviation>
    <referenceNumber>14</referenceNumber>
    <sequenceNumber>52</sequenceNumber>
    <expectedChapters>36,37</expectedChapters>
    <SBLAbbreviation>2 Chr</SBLAbbreviation>
    <OSISAbbreviation>2Chr</OSISAbbreviation>
    <SwordAbbreviation>2Chr</SwordAbbreviation>
    <CCELNumber>14</CCELNumber>
    <USFMAbbreviation>2Ch</USFMAbbreviation>
    <USFMNumber>14</USFMNumber>
    <USXNumber>014</USXNumber>
    <BibleditNumber>14</BibleditNumber>
    <NETBibleAbbreviation>2Ch</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <!-- Don't use this for combined Ezra-Nehemiah (use EZN) -->
    <nameEnglish>Ezra / 1 Ezra / 1 Esdras</nameEnglish>
    <referenceAbbreviation>EZR</referenceAbbreviation>
    <referenceNumber>15</referenceNumber>
    <sequenceNumber>60</sequenceNumber>
    <expectedChapters>10</expectedChapters>
    <SBLAbbreviation>Ezra</SBLAbbreviation>
    <OSISAbbreviation>Ezra</OSISAbbreviation>
    <SwordAbbreviation>Ezra</SwordAbbreviation>
    <CCELNumber>15</CCELNumber>
    <USFMAbbreviation>Ezr</USFMAbbreviation>
    <USFMNumber>15</USFMNumber>
    <USXNumber>015</USXNumber>
    <BibleditNumber>15</BibleditNumber>
    <NETBibleAbbreviation>Ezr</NETBibleAbbreviation>
    <possibleAlternativeBooks>EZN</possibleAlternativeBooks>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Nehemiah / 2 Ezra / 2 Esdras</nameEnglish>
    <referenceAbbreviation>NEH</referenceAbbreviation>
    <referenceNumber>16</referenceNumber>
    <sequenceNumber>70</sequenceNumber>
    <expectedChapters>13</expectedChapters>
    <SBLAbbreviation>Neh</SBLAbbreviation>
    <OSISAbbreviation>Neh</OSISAbbreviation>
    <SwordAbbreviation>Neh</SwordAbbreviation>
    <CCELNumber>16</CCELNumber>
    <USFMAbbreviation>Neh</USFMAbbreviation>
    <USFMNumber>16</USFMNumber>
    <USXNumber>016</USXNumber>
    <BibleditNumber>16</BibleditNumber>
    <NETBibleAbbreviation>Neh</NETBibleAbbreviation>
    <possibleAlternativeBooks>EZN</possibleAlternativeBooks>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Esther</nameEnglish>
    <referenceAbbreviation>EST</referenceAbbreviation>
    <referenceNumber>17</referenceNumber>
    <sequenceNumber>80</sequenceNumber>
    <expectedChapters>10</expectedChapters>
    <SBLAbbreviation>Esth</SBLAbbreviation>
    <OSISAbbreviation>Esth</OSISAbbreviation>
    <SwordAbbreviation>Esth</SwordAbbreviation>
    <CCELNumber>17</CCELNumber>
    <USFMAbbreviation>Est</USFMAbbreviation>
    <USFMNumber>17</USFMNumber>
    <USXNumber>017</USXNumber>
    <BibleditNumber>17</BibleditNumber>
    <NETBibleAbbreviation>Est</NETBibleAbbreviation>
    <possibleAlternativeBooks>ESG,ESA,ESC</possibleAlternativeBooks>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Job</nameEnglish>
    <referenceAbbreviation>JOB</referenceAbbreviation>
    <referenceNumber>18</referenceNumber>
    <sequenceNumber>90</sequenceNumber>
    <expectedChapters>42</expectedChapters>
    <SBLAbbreviation>Job</SBLAbbreviation>
    <OSISAbbreviation>Job</OSISAbbreviation>
    <SwordAbbreviation>Job</SwordAbbreviation>
    <CCELNumber>18</CCELNumber>
    <USFMAbbreviation>Job</USFMAbbreviation>
    <USFMNumber>18</USFMNumber>
    <USXNumber>018</USXNumber>
    <BibleditNumber>18</BibleditNumber>
    <NETBibleAbbreviation>Job</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Psalms / Gallicanum / Psalms A</nameEnglish>
    <referenceAbbreviation>PSA</referenceAbbreviation>
    <referenceNumber>19</referenceNumber>
    <sequenceNumber>100</sequenceNumber>
    <expectedChapters>150,151</expectedChapters>
    <SBLAbbreviation>Ps</SBLAbbreviation>
    <OSISAbbreviation>Ps</OSISAbbreviation>
    <SwordAbbreviation>Ps</SwordAbbreviation>
    <CCELNumber>19</CCELNumber>
    <USFMAbbreviation>Psa</USFMAbbreviation>
    <USFMNumber>19</USFMNumber>
    <USXNumber>019</USXNumber>
    <BibleditNumber>19</BibleditNumber>
    <NETBibleAbbreviation>Psa</NETBibleAbbreviation>
    <possibleAlternativeBooks>PB1,PB2,PB3,PB4,PB5</possibleAlternativeBooks>
  </BibleBookCodes>
  <BibleBookCodes>
    <!-- Proverbs in the Ethiopian canon is shorter than in the European canon -->
    <nameEnglish>Proverbs</nameEnglish>
    <referenceAbbreviation>PRO</referenceAbbreviation>
    <referenceNumber>20</referenceNumber>
    <sequenceNumber>110</sequenceNumber>
    <expectedChapters>31</expectedChapters>
    <SBLAbbreviation>Prov</SBLAbbreviation>
    <OSISAbbreviation>Prov</OSISAbbreviation>
    <SwordAbbreviation>Prov</SwordAbbreviation>
    <CCELNumber>20</CCELNumber>
    <USFMAbbreviation>Pro</USFMAbbreviation>
    <USFMNumber>20</USFMNumber>
    <USXNumber>020</USXNumber>
    <BibleditNumber>20</BibleditNumber>
    <NETBibleAbbreviation>Pro</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Ecclesiastes / Qoholeth</nameEnglish>
    <!-- For Ecclesiasticus use code SIR -->
    <referenceAbbreviation>ECC</referenceAbbreviation>
    <referenceNumber>21</referenceNumber>
    <sequenceNumber>120</sequenceNumber>
    <expectedChapters>12</expectedChapters>
    <SBLAbbreviation>Eccl</SBLAbbreviation>
    <OSISAbbreviation>Eccl</OSISAbbreviation>
    <SwordAbbreviation>Eccl</SwordAbbreviation>
    <CCELNumber>21</CCELNumber>
    <USFMAbbreviation>Ecc</USFMAbbreviation>
    <USFMNumber>21</USFMNumber>
    <USXNumber>021</USXNumber>
    <BibleditNumber>21</BibleditNumber>
    <NETBibleAbbreviation>Ecc</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Song of Solomon / Song of Songs / Canticles / Canticle of Canticles</nameEnglish>
    <referenceAbbreviation>SNG</referenceAbbreviation>
    <referenceNumber>22</referenceNumber>
    <sequenceNumber>130</sequenceNumber>
    <expectedChapters>8</expectedChapters>
    <SBLAbbreviation>Song</SBLAbbreviation>
    <OSISAbbreviation>Song</OSISAbbreviation>
    <SwordAbbreviation>Song</SwordAbbreviation>
    <CCELNumber>22</CCELNumber>
    <USFMAbbreviation>Sng</USFMAbbreviation>
    <USFMNumber>22</USFMNumber>
    <USXNumber>022</USXNumber>
    <BibleditNumber>22</BibleditNumber>
    <NETBibleAbbreviation>Sos</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Isaiah</nameEnglish>
    <referenceAbbreviation>ISA</referenceAbbreviation>
    <referenceNumber>23</referenceNumber>
    <sequenceNumber>132</sequenceNumber>
    <expectedChapters>66</expectedChapters>
    <SBLAbbreviation>Isa</SBLAbbreviation>
    <OSISAbbreviation>Isa</OSISAbbreviation>
    <SwordAbbreviation>Isa</SwordAbbreviation>
    <CCELNumber>23</CCELNumber>
    <USFMAbbreviation>Isa</USFMAbbreviation>
    <USFMNumber>23</USFMNumber>
    <USXNumber>023</USXNumber>
    <BibleditNumber>23</BibleditNumber>
    <NETBibleAbbreviation>Isa</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Jeremiah</nameEnglish>
    <referenceAbbreviation>JER</referenceAbbreviation>
    <referenceNumber>24</referenceNumber>
    <sequenceNumber>134</sequenceNumber>
    <expectedChapters>52</expectedChapters>
    <SBLAbbreviation>Jer</SBLAbbreviation>
    <OSISAbbreviation>Jer</OSISAbbreviation>
    <SwordAbbreviation>Jer</SwordAbbreviation>
    <CCELNumber>24</CCELNumber>
    <USFMAbbreviation>Jer</USFMAbbreviation>
    <USFMNumber>24</USFMNumber>
    <USXNumber>024</USXNumber>
    <BibleditNumber>24</BibleditNumber>
    <NETBibleAbbreviation>Jer</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Lamentations of Jeremiah</nameEnglish>
    <referenceAbbreviation>LAM</referenceAbbreviation>
    <referenceNumber>25</referenceNumber>
    <sequenceNumber>136</sequenceNumber>
    <expectedChapters>5</expectedChapters>
    <SBLAbbreviation>Lam</SBLAbbreviation>
    <OSISAbbreviation>Lam</OSISAbbreviation>
    <SwordAbbreviation>Lam</SwordAbbreviation>
    <CCELNumber>25</CCELNumber>
    <USFMAbbreviation>Lam</USFMAbbreviation>
    <USFMNumber>25</USFMNumber>
    <USXNumber>025</USXNumber>
    <BibleditNumber>25</BibleditNumber>
    <NETBibleAbbreviation>Lam</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Ezekiel</nameEnglish>
    <referenceAbbreviation>EZK</referenceAbbreviation>
    <referenceNumber>26</referenceNumber>
    <sequenceNumber>138</sequenceNumber>
    <expectedChapters>48</expectedChapters>
    <SBLAbbreviation>Ezek</SBLAbbreviation>
    <OSISAbbreviation>Ezek</OSISAbbreviation>
    <SwordAbbreviation>Ezek</SwordAbbreviation>
    <CCELNumber>26</CCELNumber>
    <USFMAbbreviation>Ezk</USFMAbbreviation>
    <USFMNumber>26</USFMNumber>
    <USXNumber>026</USXNumber>
    <BibleditNumber>26</BibleditNumber>
    <NETBibleAbbreviation>Eze</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Daniel</nameEnglish>
    <referenceAbbreviation>DAN</referenceAbbreviation>
    <referenceNumber>27</referenceNumber>
    <sequenceNumber>140</sequenceNumber>
    <expectedChapters>12,14</expectedChapters>
    <SBLAbbreviation>Dan</SBLAbbreviation>
    <OSISAbbreviation>Dan</OSISAbbreviation>
    <SwordAbbreviation>Dan</SwordAbbreviation>
    <CCELNumber>27</CCELNumber>
    <USFMAbbreviation>Dan</USFMAbbreviation>
    <USFMNumber>27</USFMNumber>
    <USXNumber>027</USXNumber>
    <BibleditNumber>27</BibleditNumber>
    <NETBibleAbbreviation>Dan</NETBibleAbbreviation>
    <possibleAlternativeBooks>DAG,DAA,DAC</possibleAlternativeBooks>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Hosea</nameEnglish>
    <referenceAbbreviation>HOS</referenceAbbreviation>
    <referenceNumber>28</referenceNumber>
    <sequenceNumber>152</sequenceNumber>
    <expectedChapters>14</expectedChapters>
    <SBLAbbreviation>Hos</SBLAbbreviation>
    <OSISAbbreviation>Hos</OSISAbbreviation>
    <SwordAbbreviation>Hos</SwordAbbreviation>
    <CCELNumber>28</CCELNumber>
    <USFMAbbreviation>Hos</USFMAbbreviation>
    <USFMNumber>28</USFMNumber>
    <USXNumber>028</USXNumber>
    <BibleditNumber>28</BibleditNumber>
    <NETBibleAbbreviation>Hos</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Joel</nameEnglish>
    <referenceAbbreviation>JOL</referenceAbbreviation>
    <referenceNumber>29</referenceNumber>
    <sequenceNumber>154</sequenceNumber>
    <expectedChapters>3,4</expectedChapters>
    <SBLAbbreviation>Joel</SBLAbbreviation>
    <OSISAbbreviation>Joel</OSISAbbreviation>
    <CCELNumber>29</CCELNumber>
    <USFMAbbreviation>Jol</USFMAbbreviation>
    <USFMNumber>29</USFMNumber>
    <USXNumber>029</USXNumber>
    <BibleditNumber>29</BibleditNumber>
    <NETBibleAbbreviation>Joe</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Amos</nameEnglish>
    <referenceAbbreviation>AMO</referenceAbbreviation>
    <referenceNumber>30</referenceNumber>
    <sequenceNumber>156</sequenceNumber>
    <expectedChapters>9</expectedChapters>
    <SBLAbbreviation>Amos</SBLAbbreviation>
    <OSISAbbreviation>Amos</OSISAbbreviation>
    <SwordAbbreviation>Amos</SwordAbbreviation>
    <CCELNumber>30</CCELNumber>
    <USFMAbbreviation>Amo</USFMAbbreviation>
    <USFMNumber>30</USFMNumber>
    <USXNumber>030</USXNumber>
    <BibleditNumber>30</BibleditNumber>
    <NETBibleAbbreviation>Amo</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Obadiah</nameEnglish>
    <referenceAbbreviation>OBA</referenceAbbreviation>
    <referenceNumber>31</referenceNumber>
    <sequenceNumber>158</sequenceNumber>
    <expectedChapters>1</expectedChapters>
    <SBLAbbreviation>Obad</SBLAbbreviation>
    <OSISAbbreviation>Obad</OSISAbbreviation>
    <SwordAbbreviation>Obad</SwordAbbreviation>
    <CCELNumber>31</CCELNumber>
    <USFMAbbreviation>Oba</USFMAbbreviation>
    <USFMNumber>31</USFMNumber>
    <USXNumber>031</USXNumber>
    <BibleditNumber>31</BibleditNumber>
    <NETBibleAbbreviation>Oba</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Jonah</nameEnglish>
    <referenceAbbreviation>JNA</referenceAbbreviation>
    <referenceNumber>32</referenceNumber>
    <sequenceNumber>160</sequenceNumber>
    <expectedChapters>4</expectedChapters>
    <SBLAbbreviation>Jonah</SBLAbbreviation>
    <OSISAbbreviation>Jonah</OSISAbbreviation>
    <SwordAbbreviation>Jonah</SwordAbbreviation>
    <CCELNumber>32</CCELNumber>
    <USFMAbbreviation>Jon</USFMAbbreviation>
    <USFMNumber>32</USFMNumber>
    <USXNumber>032</USXNumber>
    <BibleditNumber>32</BibleditNumber>
    <NETBibleAbbreviation>Jon</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Micah</nameEnglish>
    <referenceAbbreviation>MIC</referenceAbbreviation>
    <referenceNumber>33</referenceNumber>
    <sequenceNumber>162</sequenceNumber>
    <expectedChapters>7</expectedChapters>
    <SBLAbbreviation>Nic</SBLAbbreviation>
    <OSISAbbreviation>Mic</OSISAbbreviation>
    <SwordAbbreviation>Mic</SwordAbbreviation>
    <CCELNumber>33</CCELNumber>
    <USFMAbbreviation>Mic</USFMAbbreviation>
    <USFMNumber>33</USFMNumber>
    <USXNumber>033</USXNumber>
    <BibleditNumber>33</BibleditNumber>
    <NETBibleAbbreviation>Mic</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Nahum</nameEnglish>
    <referenceAbbreviation>NAH</referenceAbbreviation>
    <referenceNumber>34</referenceNumber>
    <sequenceNumber>164</sequenceNumber>
    <expectedChapters>3</expectedChapters>
    <SBLAbbreviation>Nah</SBLAbbreviation>
    <OSISAbbreviation>Nah</OSISAbbreviation>
    <SwordAbbreviation>Nah</SwordAbbreviation>
    <CCELNumber>34</CCELNumber>
    <USFMAbbreviation>Nam</USFMAbbreviation>
    <USFMNumber>34</USFMNumber>
    <USXNumber>034</USXNumber>
    <BibleditNumber>34</BibleditNumber>
    <NETBibleAbbreviation>Nah</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>